[package]
name = "service-boilerplate"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
workspace.anyhow = true
workspace.axum = true
workspace.mango-service = true
workspace.prometheus = true
workspace.serde = true
workspace.tokio = true
workspace.tracing = true
