[package]
name = "typed-store-derive"
version = "0.3.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
eyre.workspace = true
rocksdb.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
typed-store.workspace = true
