[package]
name = "MainPackage"
version = "0.0.1"

[dependencies]
Mgo = { local = "../../../../crates/mgo-framework/packages/mgo-framework" }
DepPackage = { local = "../dep_package" }

[addresses]
main_package = "0x0"
