[package]
name = "mgo-graphql-rpc-headers"
version = "0.1.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum.workspace = true

workspace-hack.workspace = true
