[package]
name = "mgo-upgrade-compatibility-transactional-tests"
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dev-dependencies]
anyhow.workspace = true
datatest-stable.workspace = true
insta.workspace = true
move-compiler.workspace = true
move-package.workspace = true
move-binary-format.workspace = true
move-command-line-common.workspace = true
mgo-move-build.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
workspace-hack.workspace = true
