[package]
name = "mgo-verifier-transactional-tests"
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dev-dependencies]
datatest-stable.workspace = true
mgo-transactional-test-runner.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
workspace-hack.workspace = true
