[package]
name = "test-cluster"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
futures.workspace = true
tracing.workspace = true
jsonrpsee.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
rand.workspace = true
mgo-config.workspace = true
mgo-core = { workspace = true, features = ["test-utils"] }
mgo-framework.workspace = true
mgo-swarm-config.workspace = true
mgo-json-rpc.workspace = true
mgo-json-rpc-types.workspace = true
mgo-node.workspace = true
mgo-protocol-config.workspace = true
mgo-swarm.workspace = true
mgo-types = { workspace = true, features = ["test-utils"] }
prometheus.workspace = true
mgo-keys.workspace = true
mgo-sdk.workspace = true
mgo-test-transaction-builder.workspace = true

move-binary-format.workspace = true
workspace-hack.workspace = true

[target.'cfg(msim)'.dependencies]
mgo-simulator.workspace = true
fastcrypto-zkp.workspace = true

[dev-dependencies]
mgo-json-rpc-api.workspace = true
mgo-macros.workspace = true
