[package]
name = "mgo-rpc-loadgen"
version.workspace = true
edition = "2021"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
serde.workspace = true
tonic.workspace = true
futures.workspace = true
dirs.workspace = true
dashmap.workspace = true
itertools.workspace = true

shellexpand.workspace = true

mgo-types = { workspace = true, features = ["test-utils"]}
mgo-keys.workspace = true
mgo-sdk.workspace = true
telemetry-subscribers.workspace = true
mgo-json-rpc.workspace = true
mgo-json-rpc-types.workspace = true
strum.workspace = true
shared-crypto.workspace = true
serde_json.workspace = true
strum_macros.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
test-cluster.workspace = true


[[bin]]
name = "mgo-rpc-loadgen"
path = "src/main.rs"
