[package]
name = "mgo-enum-compat-util"
version = "0.1.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde_yaml.workspace = true
workspace-hack.workspace = true
