[package]
name = "mgo-package-resolver"
version = "0.1.0"
edition = "2021"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
bcs.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
mgo-types.workspace = true
thiserror.workspace = true
mgo-rest-api.workspace = true
tokio.workspace = true
eyre.workspace = true
serde.workspace = true
lru.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
hyper.workspace = true
insta.workspace = true
move-compiler.workspace = true
serde_json.workspace = true
mgo-move-build.workspace = true
tower.workspace = true
