[package]
name = "mgo-transactional-test-runner"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
bcs.workspace = true
bimap.workspace = true
clap.workspace = true
eyre.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
tempfile.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde_json.workspace = true

fastcrypto.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
move-transactional-test-runner.workspace = true
telemetry-subscribers.workspace = true

move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

rocksdb.workspace = true
simulacrum.workspace = true
mgo-graphql-rpc.workspace = true
mgo-rest-api.workspace = true
mgo-swarm-config.workspace = true
mgo-config.workspace = true
mgo-core = { workspace = true, features = ["test-utils"] }
mgo-framework.workspace = true
mgo-protocol-config.workspace = true
mgo-types = { workspace = true, features = ["test-utils"]}
mgo-json-rpc-types.workspace = true
mgo-json-rpc.workspace = true
mgo-json-rpc-api.workspace = true
mgo-framework-snapshot.workspace = true
mgo-storage.workspace = true
typed-store.workspace = true
typed-store-derive.workspace = true
workspace-hack.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
