[package]
name = "mgo-swarm-config"
version = "0.0.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
anyhow.workspace = true
fastcrypto.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tempfile.workspace = true
tracing.workspace = true
prometheus.workspace = true

move-bytecode-utils.workspace = true
narwhal-config.workspace = true
shared-crypto.workspace = true
mgo-config.workspace = true
mgo-macros.workspace = true
mgo-protocol-config.workspace = true
mgo-types.workspace = true
mgo-genesis-builder.workspace = true
workspace-hack.workspace = true

[target.'cfg(msim)'.dependencies]
mgo-simulator.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true

mgo-execution.workspace = true
