[package]
name = "mgo-transaction-checks"
version = "0.1.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
once_cell.workspace = true
mgo-macros.workspace = true
mgo-config.workspace = true
mgo-protocol-config.workspace = true
mgo-types.workspace = true
tracing.workspace = true
mgo-execution.workspace = true
fastcrypto-zkp.workspace = true
workspace-hack.workspace = true
