[package]
name = "Kiosk"
version = "0.0.1"

# for Mgo testnet
published-at = "0x43bb2146b6d4985f3b4a9538ae9187eccc1d9d6e4d9f54bc569164951d8eeeb1"

[dependencies]
Mgo = { local = "../crates/mgo-framework/packages/mgo-framework" }

[addresses]
kiosk = "0x0"
