[package]
name = "mgo-source-validation-service"
version = "0.1.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "mgo-source-validation-service"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
clap.workspace = true
hyper = "0.14"
jsonrpsee.workspace = true
tempfile = "3.3.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml = { version = "0.7.4", features = ["preserve_order"] }
tracing = "0.1.36"
serde = { version = "1.0.144", features = ["derive"] }
url = "2.3.1"

mgo-move.workspace = true
mgo-move-build.workspace = true
mgo-sdk.workspace = true
mgo-source-validation.workspace = true

axum.workspace = true
const-str.workspace = true
git-version.workspace = true
move-package.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
mango-metrics.workspace = true
prometheus.workspace = true
telemetry-subscribers.workspace = true
tower.workspace = true
tower-http.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
expect-test = "1.4.0"
fs_extra = "1.3.0"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }

mgo.workspace = true
mgo-move = { workspace = true, features = ["all"] }
mgo-json-rpc-types.workspace = true
test-cluster.workspace = true
