[package]
name = "mgo-move-natives-next-vm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
better_any.workspace = true
bcs.workspace = true
linked-hash-map = "0.5.6"
smallvec.workspace = true

fastcrypto-zkp.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
move-vm-types.workspace = true

move-stdlib = { path = "../../../external-crates/move/move-execution/next-vm/crates/move-stdlib", package = "move-stdlib-next-vm" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/next-vm/crates/move-vm-runtime", package = "move-vm-runtime-next-vm" }

mgo-protocol-config.workspace = true
mgo-types.workspace = true
workspace-hack.workspace = true
tracing.workspace = true
