[package]
name = "narwhal-worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
edition = "2021"
publish = false

[dependencies]
arc-swap.workspace = true
async-trait.workspace = true
byteorder.workspace = true
bytes.workspace = true
futures.workspace = true
governor.workspace = true
rand = { workspace = true, features = ["small_rng"] }
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tonic.workspace = true
tower.workspace = true
tracing.workspace = true
itertools.workspace = true

config = { path = "../config", package = "narwhal-config" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
network = { path = "../network", package = "narwhal-network" }
types = { path = "../types", package = "narwhal-types" }
prometheus.workspace = true
store = { path = "../../crates/typed-store", package = "typed-store" }
mango-network = { path = "../../crates/mango-network"}
mango-metrics = { path = "../../crates/mango-metrics" }
mgo-protocol-config = { path = "../../crates/mgo-protocol-config" }

anemo.workspace = true
anemo-tower.workspace = true
anyhow.workspace = true
eyre.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
arc-swap.workspace = true
rand.workspace = true
tempfile.workspace = true
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
reqwest.workspace = true
node = { path = "../node", package = "narwhal-node" }
primary = { path = "../primary", package = "narwhal-primary" }
telemetry-subscribers.workspace = true
storage = { path = "../storage", package = "narwhal-storage" }

[features]
benchmark = []
trace_transaction = []
