[package]
name = "mgo-proxy"
version = "0.0.2"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum.workspace = true
axum-server.workspace = true
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
protobuf.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
const-str.workspace = true
tower-http.workspace = true
tower.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
git-version.workspace = true
itertools.workspace = true
rand.workspace = true
reqwest.workspace = true
hyper.workspace = true
mgo-tls.workspace = true
mgo-types.workspace = true
mango-metrics.workspace = true
multiaddr.workspace = true
prometheus.workspace = true
snap.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
prost.workspace = true
once_cell.workspace = true
http-body.workspace = true


telemetry-subscribers.workspace = true
fastcrypto.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
mime.workspace = true
serde_json.workspace = true
tower.workspace = true
axum-server.workspace = true
mgo-types = { workspace = true, features = ["test-utils"] }

[build-dependencies]
prost-build.workspace = true
