[package]
name = "mgo-light-client"
version = "0.0.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
bytes.workspace = true
clap.workspace = true
move-core-types.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
serde_yaml.workspace = true
serde_json.workspace = true
mgo-types.workspace = true
mgo-config.workspace = true
mgo-rest-api.workspace = true
mgo-json.workspace = true
mgo-sdk.workspace = true
move-binary-format.workspace = true
mgo-json-rpc-types.workspace = true
mgo-package-resolver.workspace = true
workspace-hack.workspace = true

