[package]
name = "prometheus-closure-metric"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
prometheus.workspace = true
protobuf.workspace = true
workspace-hack.workspace = true
