[package]
name = "mgo-replay"
version = "0.1.0"
authors = ["MangoNet Labs <build@mangonetlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
prometheus.workspace = true
async-trait.workspace = true
jsonrpsee.workspace = true
async-recursion.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
lru.workspace = true
parking_lot.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
shellexpand.workspace = true
tempfile.workspace = true
http.workspace = true

move-vm-config.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
tokio.workspace = true
tabled.workspace = true

shared-crypto.workspace = true
mgo-config.workspace = true
mgo-core.workspace = true
mgo-execution.workspace = true
mgo-framework.workspace = true
mgo-json-rpc.workspace = true
mgo-json-rpc-api.workspace = true
mgo-json-rpc-types.workspace = true
mgo-protocol-config.workspace = true
mgo-sdk.workspace = true
mgo-storage.workspace = true
mgo-types.workspace = true
workspace-hack.workspace = true
