---
version: "3.9"
services:
  mgo-network:
    image: mangonetwork/mgo-rosetta-local
    ports:
      - "9000:9000"
    expose:
      - "9000"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/mgo start
  rosetta-online:
    image: mangonetwork/mgo-rosetta-local
    ports:
      - "9002:9002"
    expose:
      - "9002"
    working_dir: /mgo/localnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/mgo-rosetta generate-rosetta-cli-config &
        /usr/local/bin/mgo-rosetta start-online-remote-server --full-node-url http://mgo-network:9000
    stdin_open: true
    tty: true
  rosetta-offline:
    image: mangonetwork/mgo-rosetta-local
    ports:
      - "9003:9003"
    expose:
      - "9003"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/mgo-rosetta start-offline-server